routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\AboutController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\ContactController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\OrderController as ClientOrderController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

if (App::environment('production')) {
    URL::forceScheme('https');
}

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Route client
Route::get('/', [HomeController::class, 'index'])->name('client.home');

Route::get('/about', [AboutController::class, 'index'])->name('client.about');

Route::get('/shop', [ClientProductController::class, 'index'])->name('client.shop');

Route::get('/product/{category_id}', [ClientProductController::class, 'category'])->name('client.products.category');

Route::get('/product-detail/{id}', [ClientProductController::class, 'show'])->name('client.products.show');

Route::middleware('auth')->group(function () {
    Route::post('/add-to-cart', [CartController::class, 'store'])->name('client.carts.add');

    Route::get('/carts', [CartController::class, 'index'])->name('client.carts.index');

    Route::post('/update-quantity-product/{cart_product_id}', [CartController::class, 'update'])->name('client.carts.update');

    Route::post('/remove-product-in-cart/{cart_product_id}', [CartController::class, 'destroy'])->name('client.carts.remove');

    Route::post('/apply-coupon-in-product', [CartController::class, 'applyCoupon'])->name('client.carts.coupon');

    Route::get('/checkout', [CartController::class, 'checkout'])->name('client.checkout.index')->middleware('user.can_checkout_cart');

    Route::post('/process-checkout', [CartController::class, 'processCheckout'])->name('client.checkout.process')->middleware('user.can_checkout_cart');

    Route::get('/list-orders', [ClientOrderController::class, 'index'])->name('client.orders.index');

    Route::post('/order/cancel/{id}', [ClientOrderController::class, 'destroy'])->name('client.orders.cancel');

    Route::get('/contact', [ContactController::class, 'index'])->name('client.contact');
});

// Route admin
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index')->middleware('permission:list-order');

    Route::post('/update-status/{id}', [OrderController::class, 'update'])->name('orders.update')->middleware('permission:list-order');

    Route::prefix('roles')->controller(RoleController::class)->name('roles.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('role:super-admin');
        Route::post('/', 'store')->name('store')->middleware('role:super-admin');
        Route::get('/create', 'create')->name('create')->middleware('role:super-admin');
        Route::get('/{role}', 'show')->name('show')->middleware('role:super-admin');
        Route::get('/{role}/edit', 'edit')->name('edit')->middleware('role:super-admin');
        Route::put('/{role}', 'update')->name('update')->middleware('role:super-admin');
        Route::delete('/{role}', 'destroy')->name('destroy')->middleware('role:super-admin');
    });

    Route::prefix('users')->controller(UserController::class)->name('users.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('permission:show-user');
        Route::post('/', 'store')->name('store')->middleware('permission:create-user');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-user');
        Route::get('/{user}', 'show')->name('show')->middleware('permission:show-user');
        Route::get('/{user}/edit', 'edit')->name('edit')->middleware('permission:update-user');
        Route::put('/{user}', 'update')->name('update')->middleware('permission:update-user');
        Route::delete('/{user}', 'destroy')->name('destroy')->middleware('permission:delete-user');

    });

    Route::prefix('categories')->controller(CategoryController::class)->name('categories.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('permission:show-category');
        Route::post('/', 'store')->name('store')->middleware('permission:create-category');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-category');
        Route::get('/{category}', 'show')->name('show')->middleware('permission:show-category');
        Route::get('/{category}/edit', 'edit')->name('edit')->middleware('permission:update-category');
        Route::put('/{category}', 'update')->name('update')->middleware('permission:update-category');
        Route::delete('/{category}', 'destroy')->name('destroy')->middleware('permission:delete-category');
    });

    Route::prefix('products')->controller(ProductController::class)->name('products.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('permission:show-product');
        Route::post('/', 'store')->name('store')->middleware('permission:create-product');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-product');
        Route::get('/{product}', 'show')->name('show')->middleware('permission:show-product');
        Route::get('/{product}/edit', 'edit')->name('edit')->middleware('permission:update-product');
        Route::put('/{product}', 'update')->name('update')->middleware('permission:update-product');
        Route::delete('/{product}', 'destroy')->name('destroy')->middleware('permission:delete-product');
    });

    Route::prefix('coupons')->controller(CouponController::class)->name('coupons.')->group(function () {
        Route::get('/', 'index')->name('index')->middleware('permission:show-coupon');
        Route::post('/', 'store')->name('store')->middleware('permission:create-coupon');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-coupon');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-coupon');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-coupon');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-coupon');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-coupon');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\HandleImage;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use HandleImage, HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = ['name', 'email', 'password', 'phone', 'address', 'gender'];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = ['password', 'remember_token',];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = ['email_verified_at' => 'datetime',];

    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }

    public function getImagePathAttribute()
    {
        return asset($this->images->count() > 0 ? 'upload/'.$this->images->first()->url : 'upload/default.jpg');
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'LIKE', "%$name%") : null;
    }

    public function scopeWithEmail($query, $email)
    {
        return $email ? $query->where('email', 'LIKE', "%$email%") : null;
    }

    public function scopeWithPhone($query, $phone)
    {
        return $phone ? $query->where('phone', 'LIKE', "%$phone%") : null;
    }
}

app/Http/Controllers/Client/AboutController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('client.about.index');
    }
}

app/Http/Controllers/Client/CartController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\Order\CreateOrderRequest;
use App\Http\Resources\Cart\CartResource;
use App\Models\Cart;
use App\Models\CartProduct;
use App\Models\Coupon;
use App\Models\Order;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Session;

class CartController extends Controller
{
    /**
     * @var Cart $cart
     * @var Product $product
     * @var CartProduct $cartProduct
     * @var Coupon $coupon
     * @var Order $order
     */
    protected Cart $cart;
    protected Product $product;
    protected CartProduct $cartProduct;
    protected Coupon $coupon;
    protected Order $order;

    /**
     * @param Cart $cart
     * @param Product $product
     * @param CartProduct $cartProduct
     * @param Coupon $coupon
     * @param Order $order
     */
    public function __construct(Cart $cart, Product $product, CartProduct $cartProduct, Coupon $coupon, Order $order)
    {
        $this->cart = $cart;
        $this->product = $product;
        $this->cartProduct = $cartProduct;
        $this->coupon = $coupon;
        $this->order = $order;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cart = $this->cart->getCreatedBy(auth()->id())->load('products');
        return view('client.carts.index', compact('cart'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->product_size) {
            $product = $this->product->findOrFail($request->product_id);
            $cart = $this->cart->getCreatedBy(auth()->id());
            $cartProduct = $this->cartProduct->getBy($cart->id, $product->id, $request->product_size);
            if ($cartProduct) {
                $quantity = $cartProduct->product_quantity;
                $productQuantity = $quantity + $request->product_quantity;
                $cartProduct->update(['product_quantity' => $productQuantity]);
            } else {
                $dataCreated['cart_id'] = $cart->id;
                $dataCreated['product_size'] = $request->product_size;
                $dataCreated['product_quantity'] = $request->product_quantity ?? 1;
                $dataCreated['product_price'] = $product->price;
                $dataCreated['product_id'] = $request->product_id;
                $this->cartProduct->create($dataCreated);
            }
            return back()->with('message', 'Add to cart success!');
        } else {
            return back()->with('message', 'Please choose size!');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cartProduct =  $this->cartProduct->find($id);
        $dataUpdate = $request->all();
        if ($dataUpdate['product_quantity'] < 1) {
            $cartProduct->delete();
        } else {
            $cartProduct->update($dataUpdate);
        }

        $cart = $cartProduct->cart;

        return response()->json([
            'product_cart_id' => $id,
            'cart' => new CartResource($cart),
            'remove_product' => $dataUpdate['product_quantity'] < 1,
            'cart_product_price' => $cartProduct->total_price
        ], Response::HTTP_OK);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cartProduct = $this->cartProduct->findOrFail($id);
        $cartProduct->delete();
        $cart = $cartProduct->cart;
        return response()->json([
            'product_cart_id' => $id,
            'cart' => new CartResource($cart)
        ], Response::HTTP_OK);
    }

    public function applyCoupon(Request $request)
    {
        $name = $request->input('coupon_code');
        $coupon = $this->coupon->firstWithExperyDate($name, auth()->id());

        if ($coupon) {
            $message = 'Apply coupon success!';
            Session::put('coupon_id', $coupon->id);
            Session::put('coupon_code', $coupon->name);
            Session::put('coupon_value', $coupon->value);
        } else {
            Session::forget(['coupon_id', 'coupon_code', 'coupon_value']);
            $message = 'Coupon code does not exist or has expired!';
        }

        return to_route('client.carts.index')->with(['message' => $message]);
    }

    public function checkout()
    {
        $cart = $this->cart->getCreatedBy(auth()->id())->load('products');
        return view('client.carts.checkout', compact('cart'));
    }

    public function processCheckout(CreateOrderRequest $request)
    {
        $dataCreated = $request->all();
        $dataCreated['user_id'] = auth()->id();
        $dataCreated['status'] = 'pending';
        $this->order->create($dataCreated);
        $couponID = Session::get('coupon_id');
        if ($couponID) {
            $coupon = $this->coupon->find(Session::get('coupon_id'));
            if ($coupon) {
                $coupon->users()->attach(auth()->id(), ['value' => $coupon->value]);
            }
        }
        $cart = $this->cart->getCreatedBy(auth()->id());
        $cart->products()->delete();
        Session::forget(['coupon_id', 'coupon_code', 'coupon_value']);
        return to_route('client.carts.index')->with('message', 'Your order is placed successfully!');
    }
}

app/Http/Controllers/Client/ContactController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('client.contact.index');
    }
}

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\CategoryService;
use App\Services\ProductService;

class HomeController extends Controller
{
    /**
     * @var ProductService $productService
     * @var CategoryService $categoryService
     */
    protected ProductService $productService;
    protected CategoryService $categoryService;

    /**
     * @param ProductService $productService
     * @param CategoryService $categoryService
     */
    public function __construct(ProductService $productService, CategoryService $categoryService)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->productService->paginate(12);
        $categories = $this->categoryService->getParentCategory();
        return view('client.home.index', compact('products', 'categories'));
    }
}

app/Http/Controllers/Client/OrderController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Services\OrderService;

class OrderController extends Controller
{
    /**
     * @var OrderService $orderService
     */
    protected OrderService $orderService;

    /**
     * @param OrderService $orderService
     */
    public function __construct(OrderService $orderService)
    {
        $this->orderService = $orderService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->orderService->getCustomer();
        return view('client.orders.index', compact('orders'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $order = $this->orderService->findOrFail($id);
        $order->update(['status' => 'cancel']);
        return to_route('client.orders.index')->with('message', 'This order is canceled successfully!');
    }
}

resources/views/client/home/index.blade.php
@extends('client.layouts.app')
@section('title', 'Home')
@section('content')
<!-- Carousel Start -->
<div class="container-fluid mb-3">
    <div class="row px-xl-5">
        <div class="col-lg-8">
            <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                <ul class="carousel-indicators">
                    <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
                    <li data-target="#header-carousel" data-slide-to="1"></li>
                    <li data-target="#header-carousel" data-slide-to="2"></li>
                </ul>
                <div class="carousel-inner">
                    <div class="carousel-item position-relative active" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="{{asset('client/img/carousel-1.jpg')}}" style="object-fit: cover;" alt="Carousel Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Men Fashion</h1>
                                <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebut magna amet lorem magna erat diam stet. Sadi's duo stet amet amet diam elite ipsum diam</p>
                                <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="{{route('client.shop')}}">Shop Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item position-relative" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="{{asset('client/img/carousel-2.jpg')}}" style="object-fit: cover;" alt="Carousel Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Women Fashion</h1>
                                <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebut magna amet lorem magna erat diam stet. Sadi's duo stet amet amet diam elite ipsum diam</p>
                                <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="{{route('client.shop')}}">Shop Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item position-relative" style="height: 430px;">
                        <img class="position-absolute w-100 h-100" src="{{asset('client/img/carousel-3.jpg')}}" style="object-fit: cover;" alt="Carousel Image">
                        <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                            <div class="p-3" style="max-width: 700px;">
                                <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Kids Fashion</h1>
                                <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebut magna amet lorem magna erat diam stet. Sadi's duo stet amet amet diam elite ipsum diam</p>
                                <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="{{route('client.shop')}}">Shop Now</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="product-offer mb-30" style="height: 200px;">
                <img class="img-fluid" src="{{asset('client/img/offer-1.jpg')}}" alt="Offer Image">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save 20%</h6>
                    <h3 class="text-white mb-3">Special Offer</h3>
                    <a href="{{route('client.shop')}}" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
            <div class="product-offer mb-30" style="height: 200px;">
                <img class="img-fluid" src="{{asset('client/img/offer-2.jpg')}}" alt="Offer Image">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save 20%</h6>
                    <h3 class="text-white mb-3">Special Offer</h3>
                    <a href="{{route('client.shop')}}" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Carousel End -->

<!-- Featured Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
            </div>
        </div>
    </div>
</div>
<!-- Featured End -->

<!-- Categories Start -->
<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4">
        <span class="bg-secondary pr-3">Categories</span>
    </h2>
    <div class="row px-xl-5 pb-3">
        @foreach($categories as $category)
            @if($category->childrens->count() > 0)
                @foreach($category->childrens as $childCategory)
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                    <a class="text-decoration-none" href="{{route('client.products.category', ['category_id' => $childCategory->id])}}">
                        <div class="cat-item d-flex align-items-center mb-4">
                            <div class="overflow-hidden" style="width: 100px; height: 100px;">
                                <img class="img-fluid" src="{{asset('client/img/default.png')}}" alt="Default Image">
                            </div>
                            <div class="flex-fill pl-3">
                                <h6>{{$childCategory->name}}</h6>
                                <small class="text-body">{{$childCategory->products->count()}} Products</small>
                            </div>
                        </div>
                    </a>
                </div>
                @endforeach
            @else
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                    <a class="text-decoration-none" href="{{route('client.products.category', ['category_id' => $category->id])}}">
                        <div class="cat-item img-zoom d-flex align-items-center mb-4">
                            <div class="overflow-hidden" style="width: 100px; height: 100px;">
                                <img class="img-fluid" src="{{asset('client/img/default.png')}}" alt="Default Image">
                            </div>
                            <div class="flex-fill pl-3">
                                <h6>{{$category->name}}</h6>
                                <small class="text-body">{{$category->products->count()}} Products</small>
                            </div>
                        </div>
                    </a>
                </div>
            @endif
        @endforeach
    </div>
</div>
<!-- Categories End -->

<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4">
        <span class="bg-secondary pr-3">Featured Products</span>
    </h2>
    <div class="row px-xl-5" id="product">
        @foreach($products as $product)
        <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
            <div class="product-item bg-light mb-4">
                <div class="product-img position-relative overflow-hidden">
                    <img class="img-fluid w-100" src="{{$product->image_path}}" alt="Product Image">
                    <div class="product-action">
                        <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                        <a class="btn btn-outline-dark btn-square" href="{{route('client.products.show', $product->id)}}"><i class="fa fa-eye"></i></a>
                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
                    </div>
                </div>
                <div class="text-center py-4">
                    <a class="h6 text-decoration-none text-truncate" href="{{route('client.products.show', $product->id)}}">{{$product->name}}</a>
                    <div class="d-flex align-items-center justify-content-center mt-2">
                        <h5>${{number_format($product->price - $product->price * 0.2)}}</h5><h6 class="text-muted ml-2"><del>${{number_format($product->price)}}</del></h6>
                    </div>

                    <div class="d-flex align-items-center justify-content-center mb-1">
                        @php $rating = 3.5 @endphp
                        @foreach(range(1,5) as $i)
                            @if($rating > 0)
                                @if($rating > 0.5)
                                    <small class="fas fa-star text-primary mr-1"></small>
                                @else
                                    <small class="fas fa-star-half-alt text-primary mr-1"></small>
                                @endif
                            @else
                                <small class="far fa-star text-primary mr-1"></small>
                            @endif
                            @php $rating-- @endphp
                        @endforeach
                        <small>(99)</small>
                    </div>
                </div>
            </div>
        </div>
        @endforeach

        <div class="col-12 d-flex justify-content-center pb-1">
            {{$products->withQueryString()->links('pagination::bootstrap-4')}}
        </div>
    </div>
</div>
<!-- Products End -->
@endsection